# Generated by Django 4.0 on 2023-11-28 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('code', models.CharField(blank=True, max_length=5)),
                ('nickname', models.CharField(blank=True, max_length=20)),
                ('profile_image', models.ImageField(default='user_profile_image.png', upload_to=users.models.get_upload_path)),
                ('agreement_terms', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_sdp_admin', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_reformer', models.BooleanField(default=False)),
                ('is_consumer', models.BooleanField(default=False)),
                ('school', models.CharField(blank=True, max_length=20)),
                ('is_enrolled', models.CharField(blank=True, choices=[('enrolled', 'Enrolled'), ('leave_of_absence', 'LeaveOfAbsence'), ('graduated', 'Graduated')], max_length=20)),
                ('area', models.CharField(blank=True, max_length=50)),
                ('career', models.TextField(blank=True)),
                ('bios', models.TextField(blank=True)),
                ('certificate_studentship', models.ImageField(default='student_certificate_image.png', upload_to=users.models.get_upload_path)),
                ('social_provider', models.CharField(blank=True, max_length=30)),
                ('follows', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='portfolio_photo.png', upload_to=users.models.get_portfolio_photo_upload_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_photos', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='prefer_style',
            field=models.ManyToManyField(blank=True, related_name='styled_consumers', to='users.Style'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_style',
            field=models.ManyToManyField(blank=True, related_name='styled_refomers', to='users.Style'),
        ),
    ]
