# Generated by Django 5.1.1 on 2024-09-20 13:05

import django.db.models.deletion
import users.models.reformer
import users.models.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=64, unique=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("nickname", models.CharField(blank=True, max_length=20, null=True)),
                ("agreement_terms", models.BooleanField(default=False)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "profile_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=users.models.user.get_user_profile_image_upload_path,
                    ),
                ),
                ("introduce", models.TextField(blank=True, null=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("customer", "CUSTOMER"),
                            ("reformer", "REFORMER"),
                            ("admin", "ADMIN"),
                        ],
                        default="customer",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="ReformerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reformer_link", models.TextField(blank=True, null=True)),
                ("reformer_area", models.CharField(max_length=100, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reformer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reformer_profile",
            },
        ),
        migrations.CreateModel(
            name="ReformerPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=users.models.reformer.get_portfolio_upload_path,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "reformer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reformer_portfolio",
                        to="users.reformerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "reformer_portfolio",
            },
        ),
        migrations.CreateModel(
            name="ReformerMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "reformer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reformer_material",
                        to="users.reformerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReformerFreelancer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100)),
                ("client", models.CharField(max_length=100)),
                ("main_tasks", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "proof_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=users.models.reformer.get_reformer_certification_upload_path,
                    ),
                ),
                (
                    "reformer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reformer_freelancer",
                        to="users.reformerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReformerEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.CharField(max_length=100)),
                ("major", models.CharField(max_length=100)),
                ("academic_status", models.CharField(max_length=100)),
                (
                    "proof_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=users.models.reformer.get_reformer_certification_upload_path,
                    ),
                ),
                (
                    "reformer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reformer_education",
                        to="users.reformerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "reformer_education",
            },
        ),
        migrations.CreateModel(
            name="ReformerCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("issuing_authority", models.CharField(max_length=100)),
                ("issue_date", models.DateField()),
                (
                    "proof_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=users.models.reformer.get_reformer_certification_upload_path,
                    ),
                ),
                (
                    "reformer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reformer_certification",
                        to="users.reformerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReformerCareer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "proof_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=users.models.reformer.get_reformer_certification_upload_path,
                    ),
                ),
                (
                    "reformer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reformer_career",
                        to="users.reformerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReformerAwards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("organizer", models.CharField(max_length=100)),
                ("award_date", models.DateField()),
                (
                    "proof_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=users.models.reformer.get_reformer_certification_upload_path,
                    ),
                ),
                (
                    "reformer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reformer_awards",
                        to="users.reformerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReformerStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "reformer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reformer_style",
                        to="users.reformerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPreferStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefer_style", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_prefer_style",
            },
        ),
    ]
