# Generated by Django 4.0 on 2024-11-14 02:34

import uuid

import django.db.models.deletion
from django.db import migrations, models

import users.models.reformer
import users.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=64, unique=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("full_name", models.CharField(blank=True, max_length=40, null=True)),
                ("nickname", models.CharField(blank=True, max_length=20, null=True)),
                ("agreement_terms", models.BooleanField(default=False)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "profile_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=users.models.user.get_user_profile_image_upload_path,
                    ),
                ),
                ("introduce", models.TextField(blank=True, null=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("customer", "CUSTOMER"),
                            ("reformer", "REFORMER"),
                            ("admin", "ADMIN"),
                        ],
                        default="customer",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Reformer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reformer_link", models.TextField(blank=True, null=True)),
                (
                    "reformer_area",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reformer_profile",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "reformer_profile",
            },
        ),
        migrations.CreateModel(
            name="UserPreferStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefer_style", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "db_table": "user_prefer_style",
            },
        ),
        migrations.CreateModel(
            name="ReformerFreelancer",
            fields=[
                (
                    "freelancer_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("project_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "proof_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=users.models.reformer.get_reformer_certification_upload_path,
                    ),
                ),
                (
                    "reformer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reformer_freelancer",
                        to="users.reformer",
                    ),
                ),
            ],
            options={
                "db_table": "reformer_freelancer",
            },
        ),
        migrations.CreateModel(
            name="ReformerEducation",
            fields=[
                (
                    "education_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("school", models.CharField(max_length=100)),
                ("major", models.CharField(max_length=100)),
                ("academic_status", models.CharField(max_length=100)),
                (
                    "proof_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=users.models.reformer.get_reformer_certification_upload_path,
                    ),
                ),
                (
                    "reformer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reformer_education",
                        to="users.reformer",
                    ),
                ),
            ],
            options={
                "db_table": "reformer_education",
            },
        ),
        migrations.CreateModel(
            name="ReformerCertification",
            fields=[
                (
                    "certification_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("issuing_authority", models.CharField(max_length=100)),
                (
                    "proof_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=users.models.reformer.get_reformer_certification_upload_path,
                    ),
                ),
                (
                    "reformer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reformer_certification",
                        to="users.reformer",
                    ),
                ),
            ],
            options={
                "db_table": "reformer_certification",
            },
        ),
        migrations.CreateModel(
            name="ReformerCareer",
            fields=[
                (
                    "career_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("period", models.CharField(max_length=30)),
                (
                    "proof_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=users.models.reformer.get_reformer_certification_upload_path,
                    ),
                ),
                (
                    "reformer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reformer_career",
                        to="users.reformer",
                    ),
                ),
            ],
            options={
                "db_table": "reformer_career",
            },
        ),
        migrations.CreateModel(
            name="ReformerAwards",
            fields=[
                (
                    "award_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("competition", models.CharField(max_length=100)),
                ("prize", models.CharField(max_length=100)),
                (
                    "proof_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=users.models.reformer.get_reformer_certification_upload_path,
                    ),
                ),
                (
                    "reformer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reformer_awards",
                        to="users.reformer",
                    ),
                ),
            ],
            options={
                "db_table": "reformer_awards",
            },
        ),
    ]
