# Generated by Django 5.1.1 on 2024-09-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reformerprofile",
            old_name="links",
            new_name="reformer_links",
        ),
        migrations.RemoveField(
            model_name="reformerprofile",
            name="market_intro",
        ),
        migrations.RemoveField(
            model_name="reformerprofile",
            name="market_name",
        ),
        migrations.RemoveField(
            model_name="reformerprofile",
            name="nickname",
        ),
    ]
