# Generated by Django 5.1.4 on 2025-01-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="mi", max_length=20, unique=True),
        ),
    ]
