# Generated by Django 5.1.1 on 2024-09-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_reformerprofile_reformer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reformercareer",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="reformercareer",
            name="position",
        ),
        migrations.RemoveField(
            model_name="reformercareer",
            name="start_date",
        ),
        migrations.AddField(
            model_name="reformercareer",
            name="period",
            field=models.CharField(default=str, max_length=30),
            preserve_default=False,
        ),
    ]
