# Generated by Django 5.1.1 on 2024-09-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_links_reformerprofile_reformer_links_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reformerprofile",
            old_name="reformer_links",
            new_name="reformer_link",
        ),
        migrations.AddField(
            model_name="reformerprofile",
            name="reformer_area",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
