# Generated by Django 5.1.4 on 2025-01-15 13:02

import users.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                default=users.models.user.default_nickname_generator,
                max_length=100,
                unique=True,
            ),
        ),
    ]
