# Generated by Django 5.1.1 on 2024-09-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_reformercareer_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reformerportfolio",
            name="reformer",
        ),
        migrations.RemoveField(
            model_name="reformerstyle",
            name="reformer",
        ),
        migrations.RenameField(
            model_name="reformerawards",
            old_name="name",
            new_name="competition",
        ),
        migrations.RenameField(
            model_name="reformerawards",
            old_name="organizer",
            new_name="prize",
        ),
        migrations.RenameField(
            model_name="reformerfreelancer",
            old_name="main_tasks",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="reformerawards",
            name="award_date",
        ),
        migrations.RemoveField(
            model_name="reformercertification",
            name="issue_date",
        ),
        migrations.RemoveField(
            model_name="reformerfreelancer",
            name="client",
        ),
        migrations.RemoveField(
            model_name="reformerfreelancer",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="reformerfreelancer",
            name="start_date",
        ),
        migrations.DeleteModel(
            name="ReformerMaterial",
        ),
        migrations.DeleteModel(
            name="ReformerPortfolio",
        ),
        migrations.DeleteModel(
            name="ReformerStyle",
        ),
    ]
