# Generated by Django 5.1.6 on 2025-02-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="report_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
