# Generated by Django 4.0 on 2024-02-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_material_user_special_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contest_ability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contest_certification',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='etc_ability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='etc_certification',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='freelancer_ability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='freelancer_certification',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
