# Generated by Django 4.0 on 2024-03-30 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_area_remove_user_career_ability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='client',
            field=models.CharField(default='client', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 3, 31)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='main_tasks',
            field=models.TextField(default='be-coding'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='period',
            field=models.DurationField(default=datetime.timedelta(days=7)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='project_name',
            field=models.CharField(default='test_project', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='proof_document',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 3, 30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reformerprofile',
            name='nickname',
            field=models.CharField(default='nickname11', max_length=50),
            preserve_default=False,
        ),
    ]
