# Generated by Django 4.0 on 2024-06-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='proof_document',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='competition',
            name='proof_document',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='proof_document',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='internship',
            name='proof_document',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='outsourcing',
            name='proof_document',
            field=models.URLField(),
        ),
    ]
