# Generated by Django 4.0 on 2024-08-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_user_profile_image_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='introduce',
            field=models.TextField(blank=True, null=True),
        ),
    ]
