# Generated by Django 5.1.1 on 2024-09-14 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_userprofile_introduce"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internship",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="outsourcing",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="user",
            name="area",
        ),
        migrations.RemoveField(
            model_name="user",
            name="code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_consumer",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_reformer",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="social_provider",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "CUSTOMER"),
                    ("reformer", "REFORMER"),
                    ("admin", "ADMIN"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="introduce",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name="Awards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("organizer", models.CharField(max_length=100)),
                ("award_date", models.DateField()),
                ("proof_document", models.URLField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="users.reformerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("proof_document", models.URLField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career",
                        to="users.reformerprofile",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Competition",
        ),
        migrations.DeleteModel(
            name="Internship",
        ),
        migrations.DeleteModel(
            name="Outsourcing",
        ),
    ]
