# Generated by Django 5.1.1 on 2024-09-14 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_alter_user_address_alter_user_nickname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reformerprofile",
            name="major",
        ),
        migrations.RemoveField(
            model_name="reformerprofile",
            name="school",
        ),
        migrations.RemoveField(
            model_name="reformerprofile",
            name="school_certification",
        ),
        migrations.RemoveField(
            model_name="reformerprofile",
            name="status",
        ),
        migrations.CreateModel(
            name="ReformerEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.CharField(max_length=100)),
                ("major", models.CharField(max_length=100)),
                ("academic_status", models.CharField(max_length=100)),
                ("proof_document", models.URLField(null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="users.reformerprofile",
                    ),
                ),
            ],
        ),
    ]
