# Generated by Django 5.1.1 on 2024-09-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_remove_reformerprofile_major_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freelancer",
            name="period",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
