# Generated by Django 5.1.1 on 2024-09-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_remove_freelancer_period_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awards",
            name="proof_document",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="career",
            name="proof_document",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="certification",
            name="proof_document",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="freelancer",
            name="proof_document",
            field=models.URLField(null=True),
        ),
    ]
