# Generated by Django 5.1.1 on 2024-09-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_awards_proof_document_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reformerprofile",
            name="thumbnail_image",
        ),
    ]
