# Generated by Django 5.1.1 on 2024-09-15 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_remove_reformerprofile_thumbnail_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reformerprofile",
            name="special_material",
        ),
        migrations.RemoveField(
            model_name="user",
            name="prefer_style",
        ),
        migrations.RemoveField(
            model_name="reformerprofile",
            name="work_style",
        ),
        migrations.RenameField(
            model_name="awards",
            old_name="profile",
            new_name="reformer",
        ),
        migrations.RenameField(
            model_name="career",
            old_name="profile",
            new_name="reformer",
        ),
        migrations.RenameField(
            model_name="certification",
            old_name="profile",
            new_name="reformer",
        ),
        migrations.RenameField(
            model_name="freelancer",
            old_name="profile",
            new_name="reformer",
        ),
        migrations.RenameField(
            model_name="reformereducation",
            old_name="profile",
            new_name="reformer",
        ),
        migrations.CreateModel(
            name="ReformerMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "reformer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material",
                        to="users.reformerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReformerStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "reformer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style",
                        to="users.reformerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPreferStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefer_style", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Material",
        ),
        migrations.DeleteModel(
            name="Style",
        ),
    ]
