# Generated by Django 5.1.1 on 2024-09-15 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_remove_reformerprofile_special_material_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Awards",
            new_name="ReformerAwards",
        ),
        migrations.RenameModel(
            old_name="Career",
            new_name="ReformerCareer",
        ),
    ]
