# Generated by Django 5.1.1 on 2024-09-15 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_rename_awards_reformerawards_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freelancer",
            name="proof_document",
            field=models.FileField(blank=True, null=True, upload_to="freelancers/"),
        ),
        migrations.AlterField(
            model_name="reformerawards",
            name="proof_document",
            field=models.FileField(blank=True, null=True, upload_to="awards/"),
        ),
        migrations.AlterField(
            model_name="reformercareer",
            name="proof_document",
            field=models.FileField(blank=True, null=True, upload_to="careers/"),
        ),
        migrations.AlterField(
            model_name="reformereducation",
            name="proof_document",
            field=models.FileField(blank=True, null=True, upload_to="education/"),
        ),
        migrations.CreateModel(
            name="ReformerCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("issuing_authority", models.CharField(max_length=100)),
                ("issue_date", models.DateField()),
                (
                    "proof_document",
                    models.FileField(
                        blank=True, null=True, upload_to="certifications/"
                    ),
                ),
                (
                    "reformer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certification",
                        to="users.reformerprofile",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Certification",
        ),
    ]
