# Generated by Django 5.1.1 on 2024-09-15 12:03

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_alter_freelancer_proof_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freelancer",
            name="proof_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=users.models.get_certification_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="reformerawards",
            name="proof_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=users.models.get_certification_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="reformercareer",
            name="proof_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=users.models.get_certification_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="reformercertification",
            name="proof_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=users.models.get_certification_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="reformereducation",
            name="proof_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=users.models.get_certification_upload_path,
            ),
        ),
    ]
