# Generated by Django 5.1.1 on 2024-09-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_alter_freelancer_proof_document_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Freelancer",
            new_name="ReformerFreelancer",
        ),
    ]
