# Generated by Django 5.1.1 on 2024-09-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_rename_freelancer_reformerfreelancer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="follows",
        ),
        migrations.AddField(
            model_name="user",
            name="introduce",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
