version: '3'

services:
  web_local:
    container_name: web_local
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && uwsgi --ini .config/uwsgi/UPCY.ini"
    environment:
      DJANGO_SETTINGS_MODULE: UpcyProject.settings.production
    env_file:
      - .env
    volumes:
      - .:/srv/UPCY_BE
      - /tmp:/tmp
      - /var/log/uwsgi:/var/log/uwsgi
      -./logs:/UPCY_BE/logs
    expose:
      - 8000

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./.config/nginx/UPCY.conf:/etc/nginx/nginx.conf
    depends_on:
      - web_local
