version: '3'

services:
  web_local:
    container_name: web_local
    build:
      context: ./
      dockerfile: Dockerfile
    command: >
      sh -c "
      python manage.py migrate &&
      /home/ubuntu/myvenv/bin/uwsgi --ini /home/ubuntu/UPCY_BE/.config/uwsgi/UPCY.ini --logto /var/log/uwsgi/UPCY/@(exec://date +%%Y-%%m-%%d).log"
    environment:
      DJANGO_SETTINGS_MODULE: UpcyProject.settings.production
    env_file:
      - .env
    volumes:
      - .:/home/ubuntu/UPCY_BE
      - /tmp:/tmp
      - /var/log/uwsgi:/var/log/uwsgi
      - ./logs:/home/ubuntu/UPCY_BE/logs
    expose:
      - 8000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./.config/nginx/UPCY.conf:/etc/nginx/nginx.conf
    depends_on:
      - web_local
