# Generated by Django 5.1.1 on 2024-09-20 13:05

import uuid

from django.db import migrations, models

import market.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("market_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("market_name", models.CharField(max_length=50)),
                ("market_introduce", models.TextField()),
                ("market_address", models.CharField(max_length=50)),
                (
                    "market_thumbnail",
                    models.FileField(
                        upload_to=market.models.get_market_thumbnail_upload_path
                    ),
                ),
            ],
            options={
                "db_table": "market",
            },
        ),
        migrations.CreateModel(
            name="MarketService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("service_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("service_title", models.CharField(max_length=50)),
                ("service_content", models.TextField()),
                ("service_category", models.CharField(max_length=50)),
                ("service_period", models.CharField(max_length=50)),
                ("basic_price", models.IntegerField()),
                ("max_price", models.IntegerField()),
            ],
            options={
                "db_table": "market_service",
            },
        ),
        migrations.CreateModel(
            name="ServiceMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("material_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "service_material",
            },
        ),
        migrations.CreateModel(
            name="ServiceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("option_name", models.CharField(max_length=50)),
                ("option_content", models.TextField()),
                ("option_price", models.IntegerField()),
            ],
            options={
                "db_table": "service_option",
            },
        ),
        migrations.CreateModel(
            name="ServiceStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("style_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "service_style",
            },
        ),
    ]
