# Generated by Django 5.1.4 on 2025-01-13 12:41

import market.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("market_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("market_name", models.CharField(max_length=50)),
                ("market_introduce", models.TextField()),
                ("market_address", models.CharField(max_length=50)),
                (
                    "market_thumbnail",
                    models.FileField(
                        upload_to=market.models.get_market_thumbnail_upload_path
                    ),
                ),
            ],
            options={
                "db_table": "market",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("details", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "report",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("service_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("service_title", models.CharField(max_length=50)),
                ("service_content", models.TextField()),
                ("service_category", models.CharField(default="None", max_length=50)),
                ("service_period", models.PositiveIntegerField(default=0)),
                ("basic_price", models.PositiveIntegerField(default=0)),
                ("max_price", models.PositiveIntegerField(default=0)),
                ("suspended", models.BooleanField(default=False)),
                ("temporary", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "market_service",
            },
        ),
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.FileField(
                        max_length=255,
                        upload_to=market.models.get_service_image_upload_path,
                    ),
                ),
            ],
            options={
                "db_table": "market_service_image",
            },
        ),
        migrations.CreateModel(
            name="ServiceMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("material_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("material_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "market_service_material",
            },
        ),
        migrations.CreateModel(
            name="ServiceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("option_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("option_name", models.CharField(max_length=50)),
                ("option_content", models.TextField()),
                ("option_price", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "market_service_option",
            },
        ),
        migrations.CreateModel(
            name="ServiceOptionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.FileField(
                        max_length=255,
                        upload_to=market.models.get_service_option_image_upload_path,
                    ),
                ),
            ],
            options={
                "db_table": "market_service_option_image",
            },
        ),
        migrations.CreateModel(
            name="ServiceStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("style_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("style_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "market_service_style",
            },
        ),
    ]
