# Generated by Django 4.0 on 2024-11-14 02:34

import uuid

import django.db.models.deletion
from django.db import migrations, models

import market.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("market_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("market_name", models.CharField(max_length=50)),
                ("market_introduce", models.TextField()),
                ("market_address", models.CharField(max_length=50)),
                (
                    "market_thumbnail",
                    models.FileField(
                        upload_to=market.models.get_market_thumbnail_upload_path
                    ),
                ),
            ],
            options={
                "db_table": "market",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("service_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("service_title", models.CharField(max_length=50)),
                ("service_content", models.TextField()),
                ("service_category", models.CharField(default="None", max_length=50)),
                ("service_period", models.PositiveIntegerField(default=0)),
                ("basic_price", models.PositiveIntegerField(default=0)),
                ("max_price", models.PositiveIntegerField(default=0)),
                ("temporary", models.BooleanField(default=False)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_service",
                        to="market.market",
                    ),
                ),
            ],
            options={
                "db_table": "market_service",
            },
        ),
        migrations.CreateModel(
            name="ServiceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("option_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("option_name", models.CharField(max_length=50)),
                ("option_content", models.TextField()),
                ("option_price", models.PositiveIntegerField()),
                (
                    "market_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_option",
                        to="market.service",
                    ),
                ),
            ],
            options={
                "db_table": "market_service_option",
            },
        ),
        migrations.CreateModel(
            name="ServiceStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("style_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("style_name", models.CharField(max_length=50)),
                (
                    "market_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_style",
                        to="market.service",
                    ),
                ),
            ],
            options={
                "db_table": "market_service_style",
            },
        ),
        migrations.CreateModel(
            name="ServiceOptionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.FileField(
                        max_length=255,
                        upload_to=market.models.get_service_option_image_upload_path,
                    ),
                ),
                (
                    "service_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_option_image",
                        to="market.serviceoption",
                    ),
                ),
            ],
            options={
                "db_table": "market_service_option_image",
            },
        ),
        migrations.CreateModel(
            name="ServiceMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("material_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("material_name", models.CharField(max_length=50)),
                (
                    "market_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_material",
                        to="market.service",
                    ),
                ),
            ],
            options={
                "db_table": "market_service_material",
            },
        ),
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.FileField(
                        max_length=255,
                        upload_to=market.models.get_service_image_upload_path,
                    ),
                ),
                (
                    "market_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_image",
                        to="market.service",
                    ),
                ),
            ],
            options={
                "db_table": "market_service_image",
            },
        ),
    ]
