# Generated by Django 4.0 on 2024-11-14 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="reformer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="market",
                to="users.reformer",
            ),
        ),
    ]
