# Generated by Django 5.1.1 on 2024-09-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="market",
            name="market_rate",
        ),
    ]
