# Generated by Django 5.1.4 on 2025-01-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceimage",
            name="image_size",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="serviceoptionimage",
            name="image_size",
            field=models.CharField(default="", max_length=20),
        ),
    ]
