# Generated by Django 5.1.1 on 2024-10-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="temporary",
            field=models.BooleanField(default=False),
        ),
    ]
