# Generated by Django 5.1.1 on 2024-09-18 14:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_remove_market_market_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketservice",
            name="market_uuid",
            field=models.UUIDField(
                default=uuid.UUID("e67115e0-ad34-4320-8f6f-5579a48f7da9"), unique=True
            ),
        ),
    ]
