# Generated by Django 5.1.1 on 2024-09-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="servicematerial",
            table="market_service_material",
        ),
        migrations.AlterModelTable(
            name="serviceoption",
            table="market_service_option",
        ),
        migrations.AlterModelTable(
            name="servicestyle",
            table="market_service_style",
        ),
    ]
