# Generated by Django 5.1.3 on 2024-12-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="suspended",
            field=models.BooleanField(default=False),
        ),
    ]
