# Generated by Django 5.1.1 on 2024-09-18 15:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_marketservice_market_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marketservice",
            name="market_uuid",
        ),
        migrations.RemoveField(
            model_name="marketservice",
            name="service_request_count",
        ),
        migrations.RemoveField(
            model_name="marketservice",
            name="service_style",
        ),
        migrations.AddField(
            model_name="market",
            name="market_uuid",
            field=models.UUIDField(
                default=uuid.UUID("ef7e75bb-dc42-4069-acf0-c545ed00cb21"), unique=True
            ),
        ),
        migrations.AddField(
            model_name="marketservice",
            name="service_uuid",
            field=models.UUIDField(
                default=uuid.UUID("629a919e-44c9-4b5d-95f6-4745652a93f7"), unique=True
            ),
        ),
        migrations.CreateModel(
            name="ServiceMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("material_name", models.CharField(max_length=50)),
                (
                    "market_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_material",
                        to="market.marketservice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("style_name", models.CharField(max_length=50)),
                (
                    "market_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_style",
                        to="market.marketservice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
