# Generated by Django 5.1.1 on 2024-10-12 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_service_temporary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="temporary",
        ),
    ]
