# Generated by Django 5.1.1 on 2024-09-20 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_alter_servicematerial_table_and_more"),
        ("users", "0002_rename_reformerprofile_reformer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="reformer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="market",
                to="users.reformer",
            ),
        ),
    ]
