# Generated by Django 5.1.4 on 2025-01-31 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_serviceimage_image_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceimage",
            name="image_size",
        ),
        migrations.RemoveField(
            model_name="serviceoptionimage",
            name="image_size",
        ),
    ]
