# Generated by Django 5.1.1 on 2024-09-18 15:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_remove_marketservice_market_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="market_uuid",
            field=models.UUIDField(
                default=uuid.UUID("a151a991-7cdc-4d68-97ca-7c7088c38467"), unique=True
            ),
        ),
        migrations.AlterField(
            model_name="marketservice",
            name="service_uuid",
            field=models.UUIDField(
                default=uuid.UUID("72d8f1af-2d45-4178-ad53-389fdc2ccf44"), unique=True
            ),
        ),
    ]
