# Generated by Django 5.1.1 on 2024-10-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_remove_service_temporary"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="temporary",
            field=models.BooleanField(default=False),
        ),
    ]
