# Generated by Django 5.1.1 on 2025-01-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_report"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="report",
            table="report",
        ),
    ]
