# Generated by Django 5.1.1 on 2024-09-18 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0005_alter_market_market_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="market_uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="marketservice",
            name="service_uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
