# Generated by Django 5.1.1 on 2024-09-18 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0006_alter_market_market_uuid_and_more"),
        ("users", "0003_rename_reformer_links_reformerprofile_reformer_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="reformer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="market",
                to="users.reformerprofile",
            ),
        ),
    ]
