# Generated by Django 5.1.1 on 2024-09-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0006_servicematerial_material_uuid_and_more"),
        ("order", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MarketService",
            new_name="Service",
        ),
    ]
