# Generated by Django 5.1.1 on 2024-09-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0007_rename_marketservice_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="basic_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="service",
            name="max_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_category",
            field=models.CharField(default="None", max_length=50),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_period",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
