# Generated by Django 5.1.1 on 2024-09-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0008_remove_marketservice_reformer"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="servicematerial",
            table="service_material",
        ),
        migrations.AlterModelTable(
            name="servicestyle",
            table="service_style",
        ),
    ]
