# Generated by Django 5.1.1 on 2024-09-30 11:08

import django.db.models.deletion
from django.db import migrations, models

import market.models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0009_alter_serviceoption_option_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceOptionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.FileField(
                        upload_to=market.models.get_service_option_image_upload_path
                    ),
                ),
                (
                    "service_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_option_image",
                        to="market.serviceoption",
                    ),
                ),
            ],
            options={
                "db_table": "market_service_option_image",
            },
        ),
    ]
