# Generated by Django 4.0 on 2024-03-06 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_user_contest_ability_user_contest_certification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('basic_price', models.CharField(max_length=500)),
                ('info', models.TextField(blank=True)),
                ('notice', models.TextField(blank=True)),
                ('option', models.TextField(blank=True)),
                ('period', models.CharField(blank=True, max_length=100)),
                ('transaction_direct', models.BooleanField(default=False)),
                ('transaction_package', models.BooleanField(default=False)),
                ('refund', models.TextField(blank=True)),
                ('like_cnt', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.category')),
                ('detail', models.ManyToManyField(blank=True, related_name='services', to='services.Detail')),
                ('fit', models.ManyToManyField(blank=True, related_name='services', to='services.Fit')),
                ('likeuser_set', models.ManyToManyField(blank=True, related_name='liked_services', to=settings.AUTH_USER_MODEL)),
                ('reformer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='service_photo.png', upload_to=services.models.get_service_photo_upload_path)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_photos', to='services.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='style',
            field=models.ManyToManyField(blank=True, related_name='services', to='services.Style'),
        ),
        migrations.AddField(
            model_name='service',
            name='texture',
            field=models.ManyToManyField(blank=True, related_name='services', to='services.Texture'),
        ),
        migrations.CreateModel(
            name='SerivceKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='services.service')),
            ],
        ),
    ]
