# Generated by Django 5.1.1 on 2024-09-16 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="likeuser_set",
            field=models.ManyToManyField(
                blank=True, related_name="liked_services", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="reformer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="servicekeyword",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="servicephoto",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_photos",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="style",
            field=models.ManyToManyField(
                blank=True, related_name="services", to="services.style"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="texture",
            field=models.ManyToManyField(
                blank=True, related_name="services", to="services.texture"
            ),
        ),
    ]
