# Generated by Django 4.0 on 2024-03-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SerivceKeyword',
            new_name='ServiceKeyword',
        ),
    ]
