# Generated by Django 4.0 on 2024-03-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_serivcekeyword_servicekeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='max_price',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
