# Generated by Django 4.0 on 2024-06-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_created_service_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicephoto',
            name='image',
            field=models.URLField(default='service_photo.png'),
        ),
    ]
