# Generated by Django 4.0 on 2024-08-03 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userprofile_introduce'),
        ('services', '0005_alter_servicephoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='reformer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='users.user'),
        ),
    ]
