# Generated by Django 4.0 on 2024-08-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userprofile_introduce'),
        ('services', '0006_alter_service_reformer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='reformer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='users.user'),
        ),
    ]
