# Generated by Django 5.1.4 on 2025-01-15 13:53

import django.db.models.deletion
import order.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "order_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("extra_material", models.CharField(max_length=50, null=True)),
                ("additional_request", models.TextField(null=True)),
                ("service_price", models.PositiveIntegerField(null=True)),
                ("option_price", models.PositiveIntegerField(null=True)),
                ("total_price", models.PositiveIntegerField(null=True)),
                ("request_date", models.DateField(auto_now_add=True)),
                (
                    "additional_options",
                    models.ManyToManyField(
                        blank=True,
                        related_name="additional_options_order",
                        to="market.serviceoption",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="market_order",
                        to="market.market",
                    ),
                ),
                (
                    "materials",
                    models.ManyToManyField(
                        blank=True,
                        related_name="materials_order",
                        to="market.servicematerial",
                    ),
                ),
                (
                    "orderer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_order",
                        to="market.service",
                    ),
                ),
            ],
            options={
                "db_table": "order",
            },
        ),
        migrations.CreateModel(
            name="OrdererInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("orderer_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("orderer_name", models.CharField(max_length=50)),
                ("orderer_phone_number", models.CharField(max_length=50)),
                ("orderer_email", models.EmailField(max_length=254)),
                ("orderer_address", models.TextField()),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="order.order"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "orderer",
            },
        ),
        migrations.CreateModel(
            name="OrderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "image_type",
                    models.CharField(
                        choices=[("order", "order"), ("additional", "additional")],
                        max_length=20,
                    ),
                ),
                ("image_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "image",
                    models.FileField(
                        upload_to=order.models.get_order_image_upload_path
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_image",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "수락"),
                            ("rejected", "거절"),
                            ("pending", "대기"),
                            ("received", "재료 수령"),
                            ("produced", "제작 완료"),
                            ("deliver", "배송중"),
                            ("end", "거래 완료"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_status",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_status",
            },
        ),
        migrations.CreateModel(
            name="TransactionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("transaction_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "transaction_option",
                    models.CharField(
                        choices=[("pickup", "대면"), ("delivery", "택배")],
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_option",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "db_table": "transaction_option",
            },
        ),
        migrations.CreateModel(
            name="DeliveryInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("delivery_company", models.CharField(max_length=50, null=True)),
                (
                    "delivery_tracking_number",
                    models.CharField(max_length=50, null=True),
                ),
                (
                    "delivery_address",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "delivery_name",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "delivery_phone_number",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_information",
                        to="order.transactionoption",
                    ),
                ),
            ],
            options={
                "db_table": "delivery_information",
            },
        ),
    ]
