# Generated by Django 5.1.1 on 2024-09-20 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "order_category",
            },
        ),
        migrations.CreateModel(
            name="OrderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("image", models.FileField(upload_to="order_image")),
            ],
            options={
                "db_table": "order_image",
            },
        ),
        migrations.CreateModel(
            name="OrderReformFit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("fit_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "order_reform_fit",
            },
        ),
        migrations.CreateModel(
            name="OrderReformStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("style_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "order_reform_style",
            },
        ),
        migrations.CreateModel(
            name="OrderReformTexture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("texture_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "order_reform_texture",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("request_detail", models.TextField()),
                ("delivery_address", models.TextField()),
                ("size", models.CharField(max_length=50)),
                ("total_price", models.IntegerField()),
                ("request_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "transaction_option",
                    models.CharField(
                        choices=[("pickup", "대면"), ("delivery", "택배")],
                        max_length=50,
                    ),
                ),
                ("request_canceled", models.BooleanField(default=False)),
                ("portfolio_status", models.BooleanField(default=False)),
                ("additional_request", models.TextField(null=True)),
                ("payment_status", models.BooleanField(default=False)),
                ("material_received_status", models.BooleanField(default=False)),
                ("delivery_company", models.CharField(max_length=50, null=True)),
                (
                    "delivery_tracking_number",
                    models.CharField(max_length=50, null=True),
                ),
                ("kakaotalk_openchat_link", models.TextField(null=True)),
                (
                    "additional_option",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="additional_option_order",
                        to="market.serviceoption",
                    ),
                ),
            ],
            options={
                "db_table": "order",
            },
        ),
    ]
