# Generated by Django 4.0 on 2024-11-14 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0002_initial"),
        ("users", "0001_initial"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="request_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_user_order",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_order",
                to="market.service",
            ),
        ),
        migrations.AddField(
            model_name="deliveryinformation",
            name="service_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_information",
                to="order.order",
            ),
        ),
        migrations.AddField(
            model_name="additionalimage",
            name="service_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_image",
                to="order.order",
            ),
        ),
    ]
