# Generated by Django 5.1.1 on 2024-09-20 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0002_initial"),
        ("order", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="request_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_user_order",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_order",
                to="market.marketservice",
            ),
        ),
        migrations.AddField(
            model_name="ordercategory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_category",
                to="order.order",
            ),
        ),
        migrations.AddField(
            model_name="orderimage",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_image",
                to="order.order",
            ),
        ),
        migrations.AddField(
            model_name="orderreformfit",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_fit",
                to="order.order",
            ),
        ),
        migrations.AddField(
            model_name="orderreformstyle",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_style",
                to="order.order",
            ),
        ),
        migrations.AddField(
            model_name="orderreformtexture",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_texture",
                to="order.order",
            ),
        ),
    ]
