# Generated by Django 5.1.1 on 2024-11-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="request_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
