# Generated by Django 5.1.4 on 2025-01-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="rejected_reason",
            field=models.TextField(null=True),
        ),
    ]
