# Generated by Django 5.1.4 on 2025-01-16 06:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="market",
        ),
        migrations.RemoveField(
            model_name="ordererinformation",
            name="user",
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("transaction_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "transaction_option",
                    models.CharField(
                        choices=[("pickup", "대면"), ("delivery", "택배")],
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "db_table": "transaction",
            },
        ),
        migrations.AlterField(
            model_name="deliveryinformation",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_information",
                to="order.transaction",
            ),
        ),
        migrations.DeleteModel(
            name="TransactionOption",
        ),
    ]
