# Generated by Django 5.1.4 on 2025-01-16 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_remove_order_market_remove_ordererinformation_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordererinformation",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderer_information",
                to="order.order",
            ),
        ),
        migrations.AlterField(
            model_name="ordererinformation",
            name="orderer_email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
