# Generated by Django 5.1.4 on 2025-01-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_ordererinformation_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordererinformation",
            name="orderer_uuid",
        ),
    ]
