# Generated by Django 5.1.4 on 2025-01-16 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_remove_ordererinformation_orderer_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction",
                to="order.order",
            ),
        ),
    ]
