# Generated by Django 5.1.1 on 2024-09-16 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="likeuser_set",
            field=models.ManyToManyField(
                blank=True, related_name="liked_products", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="reformer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productkeyword",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productphoto",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_photos",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="style",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.style"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="texture",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.texture"
            ),
        ),
    ]
