# Generated by Django 4.0 on 2024-01-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productkeyword_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='like_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
