# Generated by Django 4.0 on 2024-01-13 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_product_like_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likeuser_set',
            field=models.ManyToManyField(blank=True, related_name='liked_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
