# Generated by Django 4.0 on 2024-01-20 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_likeuser_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='like_cnt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='likeuser_set',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
