# Generated by Django 4.0 on 2024-01-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_option_alter_product_category_alter_product_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='option',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
