# Generated by Django 4.0 on 2024-01-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_option_delete_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fit',
        ),
        migrations.AddField(
            model_name='product',
            name='fit',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='products.Fit'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='style',
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='products.Style'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='texture',
        ),
        migrations.AddField(
            model_name='product',
            name='texture',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='products.Texture'),
        ),
    ]
