# Generated by Django 4.0 on 2024-01-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_fit_product_fit_remove_product_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fit',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.Fit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.Style'),
        ),
        migrations.AlterField(
            model_name='product',
            name='texture',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.Texture'),
        ),
    ]
