# Generated by Django 4.0 on 2024-02-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_detail_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_product',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
    ]
