# Generated by Django 4.0 on 2024-03-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_is_product_product_is_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_service',
        ),
    ]
